navikt/sykepenger-im-lps-api

gradle.properties
src/main/kotlin/no/nav/helsearbeidsgiver/auth/AltinnAuthClient.kt

Oppdaterer pdp client. Ny versjon har caching av altinn token.
Legger også på logging når nytt token hentes

Bump pdp client med caching av token

---

.nais/dev.yaml

Scopet gir tilgang til dialogporten sitt api for å opprette, endre og lese dialoger i dialogporten

Legg til maskinporten scope for dialogporten i dev

---

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/KafkaConfig.kt

**Bakgrunn**
Jeg kom i skade for å brekke kafka-oppsettet vårt i denne [commiten her](https://github.com/navikt/sykepenger-im-lps-api/pull/29/commits/f3c1f8e239c41395d12c1395938d7d102de4c90c) da jeg samlet felles-ting for configen til produsenten og konsumentet. Dette sendte API-appen i crashloop i dev.
**Løsning**
Sleng på en `putAll` på propertiesene. Har verifisert at det nå funker igjen i dev.

Fiks feil med kafkaconfig

---

src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt
src/main/kotlin/no/nav/helsearbeidsgiver/innsending/InnsendingService.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/innsending/InnsendingProducer.kt
src/test/kotlin/no/nav/helsearbeidsgiver/innsending/InnsendingServiceTest.kt

**Bakgrunn**
Vi ønsker å forsikre oss at vi ikke forsøker å sende API-mottatte IMer videre til Simba i produksjon før vi er klare for dette.
**Løsning**
Lag en `IngenInnsendingProducer`, som vi bruker istedenfor `InnsendingProducer` i produksjon.

La være å sende API-mottatte inntektsmeldinger videre til Simba i produksjon

---

src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt

**Bakgrunn**
Vi trengte å gjøre en opprydning i datamodellene våre, så for å unngå for mye søl underveis stoppet vi konsumentene for inntektsmeldinger og forespørsler i produksjon.
**Løsning**
Skru på igjen konsumenter for inntektsmeldinger og forespørsler i produksjon.

Konsumer inntektsmeldinger og forespørsler i produksjon

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiver.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapperTest.kt

Før har vi bare satt `egenmeldinger = null`. Nå som vi har nødvendig data i databasen kan vi inkludere egenmeldingsdager.
Her er et eksempel på hvordan meldingen ser ut i Kafka json om sykmeldt registrer egenmeldingsdager på nav nettsiden:
```json
"sporsmals": [
{
"tekst": "Jeg er sykmeldt som",
"shortName": "ARBEIDSSITUASJON",
"svartype": "ARBEIDSSITUASJON",
"svar": "ARBEIDSTAKER"
},
{
"tekst": "Velg dagene du brukte egenmelding",
"shortName": "EGENMELDINGSDAGER",
"svartype": "DAGER",
"svar": "[\"2025-03-27\",\"2025-03-29\",\"2025-03-26\"]"
}
],
```

inkluder egenmeldingsdager i sykmelding

---

.github/workflows/main.yaml

Gjør at to deploy til dev ikke spenner bein på hverandre.
Se mer på https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency.

La workflow vente på foregående for deploy til dev

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt
src/main/kotlin/no/nav/helsearbeidsgiver/utils/SykmeldingUtils.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapperTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingUtilsTest.kt

Denne PRen bytter egenmeldingsdager i sykmelding API fra en liste av `LocalDate` til en liste av `Periode` 
(bruker `helsearbeidsgiver.domene.inntektsmelding.v1.Periode`)
Testet at det funker i dev for sykmelding med ID: `0a380626-8856-4a8a-9960-97d00cb1041e`
**Motatt data i kafka melding:**
```json
"svar": "[\"2025-03-29\",\"2025-03-30\",\"2025-03-31\"]",
```
**Vår sykmelding API respons:**
```json
"egenmeldingsdager": [
{
"fom": "2025-03-29",
"tom": "2025-03-31"
}
]
```

Bytt til hag perioder for egenmeldingsdager i sykmelding

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt

Sletter Behandler objekt i sykmelding
`behandler.navn -> navn`
`behandler.telefonnummer -> behandlerTlf`
Dette gjør formatet på variabler i sykmeldingen mer uniform og lik inntektsmeldingen som har sykmeldtNavn og sykmeldtTlf

Forenkle behandler i sykmelding

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt

Arbeidsutsikter er et objekt som aldri blir definert i syfosmaltinn, ser derfor ut til å være noe gammelt som man sluttet å støtte. 
`arbeidsutsikter` eksisterer ingen steder i syfosmaltinn main:
Her er en [link til syfosmaltinn](https://github.com/navikt/syfosmaltinn/blob/02cfd410453ace0086b72bb028fc23d3bbba60e0/src/main/kotlin/no/nav/syfo/altinn/model/SykmeldingArbeidsgiverMapper.kt#L103-L113) der prognose objektet er definert for sykmeldingen der vi ser at arbeidsutsikter ikke er inkludert (XMLPorgnose inneholder arbeidsutsikter som nullable):
```kotlin
private fun getPrognose(prognose: PrognoseAGDTO?): XMLPrognose? {
return when (prognose) {
null -> null
else -> {
val xmlPrognose = ObjectFactory().createXMLPrognose()
xmlPrognose.isErArbeidsfoerEtterEndtPeriode = …
```

Slett prognose.arbeidsutsiker da den aldri ble brukt

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt

Refaktorisert kode til å ikke bruke nullable boolean 
`periode[].aktivetet.gradertSykmelding.harReisetilskudd` ikke nullable i kafka meldingen
`prognose.erArbeidsfoerEtterEndtPeriode` ikke nullable i kafka meldingen
`periode[].aktivetet.harReisetilskudd` var true eller null, nå er den true eller false 
Disse endringen er nevnt i [migrasjon dokumentet](https://navno-my.sharepoint.com/:w:/g/personal/jesper_forrest_hustad_nav_no/EQIBJijr0LVFkoi7QK8vJO4B1B8AKNQuKDcG9m1frzR4fw?e=VfqhdG) 
(finnes i Slack `team-arbeidsgiver-internal > Bookmarks > Sykmelding migrasjon` )
Dette gjennomfører målet om å ikke bruke nullable boolean i sykmelding API.

Forenklet sykmelding kode og gjør boolean ikke nullable

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapper.kt
src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt

Det er et mål at sykmelding formatet burde forenkles der mulig.
I denne PRen blir feltet `kontaktMedPasient.behandlet` forenklet til bare `kontaktMedPasient`

forenkle kontaktMedPasient

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingService.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRoutingTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingServiceTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapperTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt

Har vært en `TODO` kommentar i koden at vi må bruke navn hentet fra PDL.
Nylig har PDL navn blitt lagt til i DTO som sykmeldtNavn.
Denne PRen bruker vi den faktiske variabelen vi har lagret istedenfor en mock verdi i sykmeldingen
Demo i dev:
```bash
TOKEN=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "orgnr=311567470" \
https://hag-lps-api-client.ekstern.dev.nav.no/systembruker |  jq -r '.tokenResponse.access_token') && \
curl -s -H "Authorization: Bearer $TOKEN" \
https://sykepenger-im-lps-api.ekstern.dev.nav.no/v1/sykmelding/0a380626-8856-4a8a-9960-97d00cb1041e | \
jq -r '.sykmeldtNavn'
RAKRYGGET FABRIKK
```

bruk ekte PDL navn istedenfor mock verdi i Sykmelding response

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapper.kt
src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt

Fra møte om sykmelding format ble vi enig om å endre formatet for å samsvare med inntektsmeldingen der mulig.
for inntektsmelding ser `arbeidsgiver` slik:
```json
"arbeidsgiver": {
"orgnr": "315587336",
"tlf": "12345678"
},
```
Denne PRen flytter orgnr inn i arbeidsgiver for å samsvare mer med dette inntektsmelding formatet:
```kotlin
data class Arbeidsgiver(
val orgnr: Orgnr,
val orgnrHovedenhet: Orgnr?,
// Navn på arbeidsgiver slik det fremkommer av sykmeldingen. Dette navnet fylles ut av lege
val navnFraBehandler: String? = null,
)
```

Flytt orgnr inn i arbeidsgiver for å samsvare med IM format

---

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapper.kt
src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt

Det er et mål at alle oppfølging relatert innhold i sykmelding skal være samlet i et objekt slik at det enklere kan ekskluderes i fremtiden.
Denne PRen samler de følgende feltene i sykmelding i `oppfoelging` variabelen:
- `meldingTilArbeidsgiver`
- `tiltakArbeidsplassen`
- `erArbeidsfoerEtterEndtPeriode`
- `beskrivHensynArbeidsplassen `

Samlet oppfølging til ett objekt

---

.nais/dev.yaml
build.gradle.kts
gradle.properties
src/main/kotlin/no/nav/helsearbeidsgiver/Application.kt
src/main/kotlin/no/nav/helsearbeidsgiver/auth/AuthClientAltinnUtils.kt
src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt
src/main/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogMelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogProducer.kt
src/main/kotlin/no/nav/helsearbeidsgiver/dialogporten/Dialogporten.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/ForespoerselTolker.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/innsending/InnsendingProducer.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/sykmelding/SykmeldingTolker.kt
src/main/kotlin/no/nav/helsearbeidsgiver/pdl/PdlService.kt
src/main/resources/application.conf
src/test/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogportenServiceTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ForespoerselIT.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/KafkaCommitOffsetTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/KafkaErrorHandlingTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/MeldingTolkerTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/testcontainer/LpsApiIntegrasjontest.kt

Oppretter dialoger ved å sende meldinger på dialog topic som ny app plukker opp
Fjerner Dialogporten klient kode da dette er flyttet til den andre applikasjonen i repo hag-dialog

Opprett dialoger med kafka

---

src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingService.kt

Vi snublet over denne da vi feilsøke i LPS-apiet. Exceptionen blir plukket opp og logget et par hakk lengre opp. Endrer til å heller logge IDen.

Ikke logg orgnr til åpne logger

---

src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt
src/main/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogMelding.kt
src/main/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogportenService.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/ForespoerselTolker.kt
src/main/kotlin/no/nav/helsearbeidsgiver/soeknad/SoeknadRepository.kt
src/main/kotlin/no/nav/helsearbeidsgiver/utils/UnleashFeatureToggles.kt
src/test/kotlin/no/nav/helsearbeidsgiver/dialogporten/DialogportenServiceTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ApplicationTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ForespoerselIT.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/KafkaCommitOffsetTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/KafkaErrorHandlingTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/MeldingTolkerTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/soeknad/SoeknadRepositoryTest.kt

**Bakgrunn**
Vi ønsker å varsle arbeidsgivere om at det er kommet en forespørsel om inntektsmelding. Denne varslingen skal skje gjennom Dialogporten, hvor forespørselen skal knyttes sammen med sykmeldingen den hører til.
**Løsning**
1. Bruk koblingen mellom vedtaksperiode og søknader som vi har lest fra status-i-speil-topicet til å finne sykmeldingen til den nyeste søknaden for vedtaksperioden i forespørselen. 
Altså: `forespørsel` -> `vedtaksperiode` -> `søknader (velger nyeste)` -> `sykmelding`.
3. Send melding til hag-dialog om at vi skal legge forespørselen til dialogen som hører til sykmeldingen vi fant i 1.

Send forespørsel om inntektsmelding til Dialogporten

---

src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ForespoerselIT.kt

**Bakgrunn**
Jeg fant noe rart i denne testen da jeg gikk gjennom testene våre for å feilsøke hvorfor testene ikke kjører grønt når vi prøver å prodsette. Nemlig at vi mocker `DialogportenService` istedenfor å bruke den `DialogportenService`-instansen som finnes inne i `services`.
**Løsning**
Bruk `services.dialogportenService` i forespørseltolkeren og mock heller Unleash.

Mock Unleash sin oppførsel i forespørselintegrasjonstest

---

src/main/resources/openapi/documentation.yaml

Det valgfrie feltet orgnr i InntektsmeldingFilterRequest kom i forrige release. Oppdaterer swagger nå før vi går ut med informasjon til LPS-leverandørene.

Oppdater swagger for å få med orgnr i request for å hente inntektsmeldinger med POST /inntektsmeldinger

---

src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselService.kt
src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/ForespoerselTolker.kt

Egen feilhåndtering som ignorer ugyldige meldinger fra import-jobben. Disse blir logget i lps-api  og tatt vare på i klienten for å undersøke senere.
Forbedret logging for å kunne spore innkommende meldinger.

ignorer ugyldige meldinger for import

---

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/pri/PriMessage.kt

Endrer parsing av forespørsel fra bro til å tillate manglende Type-felt pga en oppdatering i Bro. 
Kjører i prod for å lese inn payloads uten Type fram til vi er ajour på topic, deretter rulles denne tilbake.

tmp fix: gjør Type nullable i forespørsel

---

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/pri/PriMessage.kt
src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt

`type`-felt er fjernet fra Storebror etter å ha blitt utdatert i Simba for lenge siden.

Fjern ubrukt type-felt fra forespørsel

---

src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRouting.kt
src/main/kotlin/no/nav/helsearbeidsgiver/soeknad/SoeknadRouting.kt
src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRouting.kt
src/test/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRoutingTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/soeknad/SoeknadRoutingTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRoutingTest.kt

Så i loggene at vi fikk mange errors fordi en del sendte inn requester uten body i dev. 
Disse returnerte også 500 så litt misvisende siden det egentlig er client feil.
Catcher dette og returner bad request istedenfor.

Returner bad request ved manglende body

---

src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselService.kt

Denne skal ikke skje etter at vi legger til kafka-keys men vi legger til en error logg dersom det skjer for å kunne følge opp.

legger til errorlogging når forespørsel ikke finnes ved status endring

---

src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ApplicationTest.kt
src/test/kotlin/no/nav/helsearbeidsgiver/testcontainer/LpsApiIntegrasjontest.kt

Endret funksjonen fetchWithRetry til å få inn en betingelse som sjekker i tilleg til httpsStatus.
Denne vil gjøre at funksjonen prøver på nytt dersom meldingen ikke er prosessert.

Legger til statussjekk i fetchWithRetry for integrasjonstester

---

src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselService.kt

Endrer loggmelding til warn dersom forespørsel ikke finnes ved oppdatering av status
Bakgrunn:
Vi begynte å lagre forespørsler i produksjon fra og med 10.04.2025. Dersom det kommer en oppdatering av status for forespørsler som er eldre enn dette, vil oppdateringen feile fordi forespørselen ikke finnes.
Vi har sett en del slike tilfeller i det siste, og for å unngå unødvendig støy i loggene har vi valgt å endre loggnivået fra error til warn i disse tilfellene.

Endrer logg melding til warn

---

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/sykmelding/SykmeldingTolker.kt

Vi har logging inne i `sykmeldingService.lagreSykmelding(...)` og `dialogportenService.opprettNyDialogMedSykmelding` som faktisk forteller om vi lagrer eller oppretter dialog.

Fjern missvisende loggmelding hvor det ser ut som vi alltid lager dialog

---

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/KafkaConsumer.kt
src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/KafkaCommitOffsetTest.kt

Ikke baser kafka poll loop på coroutine context er aktiv
Sjekk at partisjoner er tildelt konsumeren før vi pauser konsumeren.

Fiks feil i kafka poll loop ved pause av konsumer
