navikt/sykepenger-im-lps-api

build.gradle.kts, gradle.properties, src/main/kotlin/no/nav/helsearbeidsgiver/db/Database.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRepository.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingService.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/MottakRepository.kt, src/main/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/InntektsmeldingKafkaConsumer.kt, src/test/kotlin/no/nav/helsearbeidsgiver/KafkaProducer.kt, src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/InntektsmeldingKafkaConsumerTest.kt, src/test/resources/im.json, src/test/resources/inntektsmelding_distribuert.json
endrer til vanlig blokkerende transaction i exposed, legger til db-test
=> database tx

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/ForespoerselKafkaConsumer.kt, src/main/resources/documentation.yaml, src/test/kotlin/no/nav/helsearbeidsgiver/KafkaProducer.kt, src/test/kotlin/no/nav/helsearbeidsgiver/kafka/inntektsmelding/ImKafkaConsumerTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt, src/test/resources/forespoersel.json, src/test/resources/inntektsmelding_distribuert.json
endret payloads etter bytte til nye kafka topics
=> nye payloads i testdata

.nais/app.yaml, build.gradle.kts, src/main/kotlin/no/nav/helsearbeidsgiver/Application.kt, src/main/kotlin/no/nav/helsearbeidsgiver/kafka/KafkaConsumerConfig.kt, src/main/resources/documentation.yaml
fjern "feil" ingress
sett unik id på hver kafkaconsumer (fjerner warn i logger)
=> kjør på to podder parallellt

.nais/app.yaml, gradle.properties
Klarte å deploye en fel i nais specen med feil scope for altinn pdp integrasjonen. 
Har også bumpet klienten til å hente token når pdp kallet skjer istedenfor ved oppstart av appen
=> Bump pdp klient med støtte for refresh token

.github/CODEOWNERS, README.md, build.gradle.kts, openApiTasks.gradle.kts, src/main/kotlin/no/nav/helsearbeidsgiver/auth/TokenValidationUtils.kt, src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselRouting.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRouting.kt, src/main/kotlin/no/nav/helsearbeidsgiver/plugins/Routing.kt, src/main/resources/documentation.yaml, src/main/resources/openapi/documentation.yaml
Denne pull requesten inkluderer flere oppdateringer for å forbedre OpenAPI-dokumentasjonen og forbedre kodebasen med bedre feilmeldinger og kommentarer. De viktigste endringene inkluderer tillegg av en Gradle-task for å modifisere OpenAPI-dokumentasjonen, oppdateringer til OpenAPI-dokumentasjonsfilen, forbedrede feilmeldinger i tokenvalidering, og lagt til kommentarer for beskrivelse av tjenestene.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R76-R83): Lagt til instruksjoner for å generere og modifisere OpenAPI-dokumentasjon ved hjelp av en ny Gradle-task.
* [`openApiTasks.gradle.kts`](diffhunk://#diff-18ae750fe66e70660405ee2326fb4aadc75d71a2de9c73d3ee4233d046192015R1-R74): Introdusert en ny Gradle-task `modifyOpenApi` for å oppdatere …
=> Swagger automatisk oppdatering av openApi dokumentasjon 

src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/Forespoersel.kt, src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselRepository.kt, src/main/resources/openapi/documentation.yaml, src/test/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselRepositoryTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselServiceTest.kt
Lar LSPS swagger-spec være camelCase siden vi deler noen klasser med simba-domain, og disse er camelCase.
(svelger noen kameler)
=> forespørsel: Tilbake til camelCase

openApiTasks.gradle.kts, src/main/resources/openapi/documentation.yaml, src/main/resources/openapi/inntektEndringAarsak.yaml
legger inn InntektEndringAarsak manuelt med modifyOpenApi-gradlejobb siden ktor openapi plugin ikke klarer å generere polymorph-objekter
=> generert ny swagger med InntektEndringAarsak

.nais/dev.yaml, .nais/prod.yaml
Token som utstedes har som default max levetid på 30 sek. Øker denne til 600 (ti minutter)
=> maskinporten token max age

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/sykmelding/SykmeldingTolker.kt
=> Bruk infologging til å logge at vi har lagret sykmelding

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingDTO.kt, src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingEntitet.kt, src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRepository.kt, src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingService.kt, src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingArbeidsgiverMapper.kt, src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRepositoryTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingRoutingTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/sykmelding/SykmeldingServiceTest.kt
Liten PR for å lagre kafka meldingen for sykmelding. Ikke endret funksjonalitet i kode.
=> Lagre kafka melding for sykmelding

build.gradle.kts, gradle.properties
Dette gjør det lettere å se hva man har tatt i koden. Fjerner også tre overflødige `io.ktor:ktor-server-core`.
=> Sortér avhengigheter

src/main/kotlin/no/nav/helsearbeidsgiver/Application.kt, src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt, src/main/kotlin/no/nav/helsearbeidsgiver/utils/UnleashFeatureToggles.kt
Ved lokal kjøring så trenger vi en falsk versjon av Unleash.
=> Kjør lokalt med FakeUnleash

src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/Sykmelding.kt, src/main/kotlin/no/nav/helsearbeidsgiver/sykmelding/model/SykmeldingMapper.kt, src/main/kotlin/no/nav/helsearbeidsgiver/utils/SykmeldingUtils.kt, src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestData.kt
Endringer:
- Samle behandler i et objekt
- Samle behandler navn til en string
- Samler sykmeldt i et objekt
- egenmeldingsdager bytt set med list
- perioder -> sykmeldingPerioder
- syketilfelleFom ->  sykefravaerFom
- mottattidspunkt ->  motattAvNav
-  ikke la sykmeldingPerioder være nullable
- Slettet @Schema descriptions som var identiske til variabelnavnet
=> V1 Sykmeldingen (etter hag diskusjon)

src/main/kotlin/no/nav/helsearbeidsgiver/Application.kt, src/main/kotlin/no/nav/helsearbeidsgiver/auth/AuthClient.kt, src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt, src/main/kotlin/no/nav/helsearbeidsgiver/pdl/PdlService.kt
Denne pull requesten introduserer refaktorering og forbedringer av AuthClient. Endringene inkluderer overgangen til å gjøre AuthClient om til et interface med flere implementasjoner, forbedret bruk av dependency injection, og sikring av miljøspesifikk oppførsel. I tillegg bruker nå PdlService-klassen samme instans av Authclient
=> Fikse lokal-kjøring av Application

.github/workflows/main.yaml, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRepository.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingResponse.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRouting.kt, src/main/resources/openapi/documentation.yaml, src/test/kotlin/no/nav/helsearbeidsgiver/testcontainer/Containers.kt
Opprettet 3 nye get endepunkter for å hente inntektsmelding basert på inntektsmeldingId, navReferanseId, status.
oppdatert swagger dokumentasjon
=> Get API for inntektsmeldinger

src/main/resources/db/migration/V16__soknad.sql
Vi ønsker å lagre søknader mottatt fra Flex, som skal sendes til arbeidsgivere, foreløpig bare i dev.
=> Opprett databasetabell for søknader

src/main/kotlin/no/nav/helsearbeidsgiver/innsending/InnsendingStatus.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRepository.kt, src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/InntektsmeldingRouting.kt, src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ApplicationTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/InntektsmeldingApiTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/testcontainer/LpsApiIntegrasjontest.kt
Nye tester
Fjernet Status UNDER_BEHANDLING etter avtale med @mortenbyhring 
Diverse refaktoreringer
=> nye testre og  refaktorering

src/main/kotlin/no/nav/helsearbeidsgiver/innsending/InnsendingService.kt, src/main/kotlin/no/nav/helsearbeidsgiver/kafka/innsending/InnsendingProducer.kt, src/test/kotlin/no/nav/helsearbeidsgiver/innsending/InnsendingServiceTest.kt
dette sikrer samme partisjon / rekkefølge på meldinger
=> bruk forespørselId som key ved sending på kafka

src/main/resources/db/migration/V19__legg_til_eksponertforesporsel.sql, src/test/resources/application.conf
Oppdatert forespørsel database skript
Legger til maglende miljø variabler for lokalkjøring
=> Oppdatert forespørsel database skript

src/main/kotlin/no/nav/helsearbeidsgiver/forespoersel/ForespoerselRouting.kt, src/main/kotlin/no/nav/helsearbeidsgiver/kafka/KafkaConsumer.kt
Fiks typo, og legg til offset og partition i errorlogg ved KafkaConsumer-feil
=> loggfikser

src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ApplicationTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/utils/ForespoerselKafkaTestData.kt, src/test/kotlin/no/nav/helsearbeidsgiver/utils/TestDataUtils.kt
Refaktorering av testdata-generator
=> refaktorering

src/main/kotlin/no/nav/helsearbeidsgiver/kafka/forespoersel/pri/PriMessage.kt
This reverts commit 067b522f66e9fde8ccf374e15f8f44154e7b3eb6.
Vi går tilbake til vanlig drift! :)
=> Revert "tmp fix: gjør Type nullable i forespørsel (#170)"

.nais/prod.yaml, build.gradle.kts, src/main/kotlin/no/nav/helsearbeidsgiver/Application.kt, src/main/kotlin/no/nav/helsearbeidsgiver/config/ApplicationConfig.kt, src/main/kotlin/no/nav/helsearbeidsgiver/kafka/sykmelding/SykmeldingTolker.kt, src/main/kotlin/no/nav/helsearbeidsgiver/pdl/PdlService.kt, src/test/kotlin/no/nav/helsearbeidsgiver/authorization/ApiTest.kt, src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/ForespoerselIT.kt, src/test/kotlin/no/nav/helsearbeidsgiver/integrasjonstest/InnsendingIT.kt, src/test/kotlin/no/nav/helsearbeidsgiver/testcontainer/LpsApiIntegrasjontest.kt
Vi har fått tilgang i til pdl i prod. 
Fjerner "dev" toggle på dette
=> Skru på pdl i prod
